apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: NodePort
  
