# values.yaml

prometheus:
  server:
    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-app:5000']  # Replace with your Flask application's hostname and port
